# Generated by Django 5.1.2 on 2024-11-14 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flowerpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the flowerpot entry was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the flowerpot entry was last updated')),
                ('name', models.CharField(help_text='Unique name for the smart flowerpot', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description or notes about the flowerpot', null=True)),
                ('location', models.CharField(blank=True, help_text="Location of the flowerpot (e.g., 'Living Room')", max_length=100, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the flowerpot entry was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the flowerpot entry was last updated')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Temperature in Celsius', max_digits=5, null=True)),
                ('moisture', models.DecimalField(blank=True, decimal_places=2, help_text='Soil moisture level', max_digits=5, null=True)),
                ('ph_level', models.DecimalField(blank=True, decimal_places=2, help_text='Soil pH level', max_digits=4, null=True)),
                ('light_level', models.DecimalField(blank=True, decimal_places=2, help_text='Light level in lumens', max_digits=5, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, help_text='Air humidity percentage', max_digits=5, null=True)),
                ('hash', models.CharField(editable=False, help_text='Unique log name generated from hash', max_length=64, unique=True)),
                ('flowerpot', models.ForeignKey(help_text='The flowerpot associated with this data reading', on_delete=django.db.models.deletion.CASCADE, related_name='environment_data', to='stat.flowerpot')),
            ],
            options={
                'verbose_name': 'Environment Data',
                'verbose_name_plural': 'Environment Data',
                'ordering': ['-created_at'],
            },
        ),
    ]
