# Generated by Django 5.1.2 on 2024-12-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environmentdata',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='environmentdata',
            name='light_level',
        ),
        migrations.RemoveField(
            model_name='environmentdata',
            name='moisture',
        ),
        migrations.RemoveField(
            model_name='environmentdata',
            name='ph_level',
        ),
        migrations.AddField(
            model_name='environmentdata',
            name='air_humidity',
            field=models.FloatField(blank=True, help_text='Air humidity percentage', null=True),
        ),
        migrations.AddField(
            model_name='environmentdata',
            name='soil_moisture',
            field=models.FloatField(blank=True, help_text='Soil moisture percentage', null=True),
        ),
        migrations.AddField(
            model_name='flowerpot',
            name='slug',
            field=models.SlugField(default=None, help_text='Unique slug for the smart flowerpot', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='environmentdata',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Temperature in degrees Celsius', null=True),
        ),
        migrations.AlterField(
            model_name='flowerpot',
            name='name',
            field=models.CharField(help_text='Unique name for the smart flowerpot', max_length=100),
        ),
    ]
