# Generated by Django 5.1.2 on 2024-12-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat', '0002_remove_environmentdata_humidity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowerpot',
            name='threshold',
            field=models.PositiveIntegerField(blank=True, default=30, help_text='Soil moisture threshold percentage', null=True),
        ),
        migrations.AlterField(
            model_name='environmentdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the flowerpot entry was created', null=None),
        ),
        migrations.AlterField(
            model_name='environmentdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the flowerpot entry was last updated', null=None),
        ),
        migrations.AlterField(
            model_name='flowerpot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the flowerpot entry was created', null=None),
        ),
        migrations.AlterField(
            model_name='flowerpot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the flowerpot entry was last updated', null=None),
        ),
    ]
